### ISSUE TITLE
conflict with firebase_auth version

### ISSUE THREAD

**Issue by terry960302** [atn832/firebase_auth_mocks#1]
version conflict between firebase_auth_mocks and firebase_auth 
need a new version of firebase_auth_mocks

```
Because every version of firebase_auth_mocks depends on firebase_auth ^0.14.0+5 and effy_app depends on firebase_auth ^0.15.2, firebase_auth_mocks is forbidden.
```

**Comment by atn832** [comment]
Just updated the library https://pub.dev/packages/firebase_auth_mocks#011.

Thanks for reporting!
