### ISSUE TITLE
The argument type 'Map<String, Object>' can't be assigned to the parameter type 'PigeonIdTokenResult'

### ISSUE THREAD

**Issue by TheodoreClemens** [atn832/firebase_auth_mocks#100]
Maybe I updated my packages but I started receiving this error while attempting to write unit tests. 

[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6.7 21G651 darwin-x64, locale en-CA)
    • Flutter version 3.10.6 on channel stable at /.../.../.../flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

Package versions: 
firebase_auth_mocks: ^0.12.0
firebase_auth: ^4.7.0

<img width="996" alt="Screen Shot 2023-07-17 at 10 59 34 PM" src="https://github.com/atn832/firebase_auth_mocks/assets/71221106/899eb5a6-a28e-489e-9c11-3a1122b4876e">

Any solutions? Thanks

SOLUTION:

I fixed it, I needed to mockAuth.signInWithEmailAndPassword() [or whichever signing method] in my setUp() function before testing. Thank you for your time

**Comment by atn832** [comment]
Hi @TheodoreClemens,

This is happening because your project is transitively depending on an older version of https://pub.dev/packages/firebase_auth_platform_interface. You can run `flutter pub upgrade` to get the latest version of the package.

See #99 for more context.
