### ISSUE TITLE
Cannot mock exceptions from `signOut`

### ISSUE THREAD

**Issue by michaelowolf** [atn832/firebase_auth_mocks#109]
Something like the following doesn't seem to result in an exception during tests:
```dart
whenCalling(Invocation.method(#signOut, null))
    .on(auth)
    .thenThrow(Exception("Couldn't sign out!"));
```

I presume this is simply because [`signOut`](https://github.com/atn832/firebase_auth_mocks/blob/master/lib/src/firebase_auth_mocks_base.dart#L167) doesn't have the `maybeThrowException` statement required by `mock_exceptions`.

I'm not sure if it's a deliberate decision or not, but currently we'd like to test error cases for signing out. If this is useful, I'd be happy to put up a PR.

**Comment by atn832** [comment]
You're right, all it needs is the `maybeThrowException` statement. The omission is simply due to lack of time. It would be amazing if you could propose a PR for this issue and #110 !

**Comment by michaelowolf** [comment]
> You're right, all it needs is the `maybeThrowException` statement. The omission is simply due to lack of time. It would be amazing if you could propose a PR for this issue and #110 !

Of course - I've raised a PR for this one at https://github.com/atn832/firebase_auth_mocks/pull/111, and I'll take a look at #110.
