### ISSUE TITLE
Add `isAnonymous` to User mock

### ISSUE THREAD

**Issue by sashako** [atn832/firebase_auth_mocks#13]
Hello,
would be great to have access to `MockUser.isAnonymous`, it seems like it should be relatively simple to do. Also happy to submit a PR.

**Comment by atn832** [comment]
Thanks for offering to contribute a PR. I'll be happy to review your PR for the next feature. :)

I just implemented it and released a new version at https://pub.dev/packages/firebase_auth_mocks/changelog#031.
