### ISSUE TITLE
What can we expect to be return from user.displayName

### ISSUE THREAD

**Issue by dimstein** [atn832/firebase_auth_mocks#15]
Hi, 
Gave it a go and got the following:
 displayName: Bob,
 uid: aabbcc.
Is this what I should expect?
If so can this info be put in the Readme.

Was using 'signInWithEmailPassword', was expecting that: user.email would return the email I enter but it returned 'null'
Thanks
Dimstein

**Comment by atn832** [comment]
Yes, you can expect Bob with uid aabbc. For the email, we should hardcode it to something other that null. I'll file a ticket.

**Comment by atn832** [comment]
Sure I can add this information to the readme for the next update.

**Comment by dimstein** [comment]
Wonderful.  I can now like.
here my code I favour using .then & expect

`import 'package:firebase_auth_mocks/firebase_auth_mocks.dart';
import 'package:flutter_test/flutter_test.dart';

main() {
  group('firestore Auth test', (){
    final auth = MockFirebaseAuth();

    test('find the user displayName', (){
      auth.signInWithEmailAndPassword(email: 'test@test.com', password: '123456')
          .then((value) => expect(value.user.displayName, 'Bob'));
    });

    test('find the user uid', (){
      auth.signInWithEmailAndPassword(email: 'test@test.com', password: '123456')
          .then((value) => expect(value.user.uid, 'aabbcc'));
    });

  });

}`
