### ISSUE TITLE
Feature Request: add photo url to the hardcoded user

### ISSUE THREAD

**Issue by ammaratef45** [atn832/firebase_auth_mocks#22]
I think it would be useful to make the hardcoded-user configurable (allow it to be created with custom data)

Also, adding a photo URL to the default one could be nice

**Comment by PieterHartzer** [comment]
I created a [PR (#25)](https://github.com/atn832/firebase_auth_mocks/pull/25) for this as the previous PR wasn't going anywhere.

**Comment by atn832** [comment]
Fixed by #25.
