### ISSUE TITLE
Implement signInWithPhoneNumber

### ISSUE THREAD

**Issue by rutaba1** [atn832/firebase_auth_mocks#23]
Hi! I could see that there is a function for signInWithPhoneNumber in the package but I'm not sure if its functional and how to use it. Any info regarding this function is appreciated.

Thanks!

**Comment by atn832** [comment]
You're right, I just implemented and published this feature at https://pub.dev/packages/firebase_auth_mocks/changelog#051. See how to use it at: https://github.com/atn832/firebase_auth_mocks/blob/3af6e333c5566e9dddb4b803cdf5855f7f24d99b/test/firebase_auth_mocks_test.dart#L52

The `MockConfirmationResult` will approve any confirmation number. If you need something fancier, feel free to propose a PR.

Related docs:

- https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/signInWithPhoneNumber.html
- https://pub.dev/documentation/firebase_auth/latest/firebase_auth/ConfirmationResult-class.html
