### ISSUE TITLE
Support for nnbd

### ISSUE THREAD

**Issue by bsutton** [atn832/firebase_auth_mocks#27]
Google is now requesting that package maintainers release a nnbd pre-release version.

**Comment by atn832** [comment]
Thanks for letting me know. I may not have the time to do it before null safety goes stable, but feel free to submit a PR and I'll happily review it.

For future reference:
- https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010
- https://dart.dev/null-safety/migration-guide

**Comment by atn832** [comment]
Resolved a few versions back.
