### ISSUE TITLE
createUserWithEmailAndPassword only returns null

### ISSUE THREAD

**Issue by emmett-deen** [atn832/firebase_auth_mocks#28]
The method createUserWithEmailAndPassword only seems to return null & none of the errors described in the documentation are thrown. It doesn't say this was explicitly implemented in the docs, so I am going to assume it wasn't implemented at all, but would be very nice to have. Being able to test all outcomes of sign up errors and how documents are created in firestore based on sign up would be extremely useful for me.

**Comment by f-hoedl** [comment]
Hey @emmett-deen,
you are right with your assumption, that this is not implemented. 
This response is very late, but I hope this can help anyway. 

I created a pull request to implement this method.
https://github.com/atn832/firebase_auth_mocks/pull/51

**Comment by atn832** [comment]
Fixed thanks to @f-hoedl's https://github.com/atn832/firebase_auth_mocks/pull/51. You can get it with the latest version of the package: https://pub.dev/packages/firebase_auth_mocks/changelog#083..
