### ISSUE TITLE
Feature Request: Add support to mock sendSignInWithEmailLink 

### ISSUE THREAD

**Issue by RounakTadvi** [atn832/firebase_auth_mocks#33]
Add support for mocking 
```sh
sendSignInWithEmailLink({
    required String email,
    required ActionCodeSettings actionCodeSettings,
  }) 
```
method

**Comment by atn832** [comment]
Thanks for filing this ticket. I'll be happy to review a PR if you can contribute one.

**Comment by RounakTadvi** [comment]
Okay @atn832

**Comment by atn832** [comment]
Implemented in https://github.com/atn832/firebase_auth_mocks/commit/8461bdb0eb01606b2945b40ca7e1688391ec6320. You can get it from the latest version.
