### ISSUE TITLE
Feature request: support "userChanges"

### ISSUE THREAD

**Issue by eggnstone** [atn832/firebase_auth_mocks#34]
Please implement the userChanges stream.

**Comment by mazzonem** [comment]
I just created a PR (https://github.com/atn832/firebase_auth_mocks/pull/37) for this.

**Comment by atn832** [comment]
Thank you @eggnstone for reporting the issue and @mazzonem for submiting a fix. I've published your PR at https://pub.dev/packages/firebase_auth_mocks/changelog#081.
