### ISSUE TITLE
Version solving fails with `firebase_auth` 2.0.0

### ISSUE THREAD

**Issue by andre-paraense** [atn832/firebase_auth_mocks#38]
$ flutter pub get

Because firebase_auth_mocks 0.7.1 depends on firebase_auth ^1.3.0 and <PROJECT> depends on firebase_auth 2.0.0, firebase_auth_mocks 0.7.1 is forbidden.
So, because <PROJECT> depends on firebase_auth_mocks 0.7.1, version solving failed.
Running "flutter pub get" in <PROJECT>...              
pub get failed (1; So, because <PROJECT> depends on firebase_auth_mocks 0.7.1, version solving
failed.)

**Comment by bretmh** [comment]
Until they update it just use firebase_auth: ^1.3.0

**Comment by hnvn** [comment]
`firebase_auth` version is 3.0.0 now

**Comment by atn832** [comment]
Hi everyone, I just published version 0.8.0 which uses `firebase_auth ` version 3.0.0. https://github.com/atn832/firebase_auth_mocks/commit/a7737cda0fba20796e504109ebc124c9e834174f.
