### ISSUE TITLE
Class 'MockUser' has no instance method 'reload' with matching arguments.

### ISSUE THREAD

**Issue by oudehomar** [atn832/firebase_auth_mocks#39]
I'm trying to mock a firestore call in a test with a mocked user but im getting: 
`NoSuchMethodError: Class 'MockUser' has no instance method 'reload' with matching arguments.
Receiver: Instance of 'MockUser'
Tried calling: reload()
Found: reload() => Future<void>`
the methods: 
https://stackoverflow.com/questions/68411559/mocking-firebase-user-reload-in-flutter-test

**Comment by atn832** [comment]
Thanks for filing. I just implemented the method at https://github.com/atn832/firebase_auth_mocks/commit/a7737cda0fba20796e504109ebc124c9e834174f and published it as version 0.8.0. See https://pub.dev/packages/firebase_auth_mocks/changelog#080.

**Comment by oudehomar** [comment]
Thank you, i think i'll add some more issues soon

**Comment by oudehomar** [comment]
@atn832  You could thank me there too ;) .. i think i'll add some more issues soon. Be prepared ;)
