### ISSUE TITLE
No implementation of User.delete and User.reauthenticateWithCredential

### ISSUE THREAD

**Issue by ChopinDavid** [atn832/firebase_auth_mocks#43]
I went ahead and forked this repo and implemented these two methods as would work for me. I feel that [my `User.delete` implementation commit](https://github.com/ChopinDavid/firebase_auth_mocks/commit/55d5ad3ec3cf3f14f6656515f2ab1251df58d2fc) is definitely worth pulling in (it is basically the same as [`a7737cd`](https://github.com/atn832/firebase_auth_mocks/commit/a7737cda0fba20796e504109ebc124c9e834174f)), but I am unsure if [my implementation of `User.reauthenticateWithCredential`](https://github.com/ChopinDavid/firebase_auth_mocks/commit/f4346d854c3d2797ffa92b172d4634740ad0cf6b) would break tests that others have written. I also went ahead and [wrote tests](https://github.com/ChopinDavid/firebase_auth_mocks/commit/3745577a0469e4ce773396a4d0eb112149581f2c) around my implementations.

The fork can be found [here](https://github.com/ChopinDavid/firebase_auth_mocks). Let me know if there is anything you feel is worth making a PR for.

**Comment by atn832** [comment]
I am so sorry, I just saw this ticket. I would gladly have merged your PR had I seen this earlier. I literally just merged and published https://github.com/atn832/firebase_auth_mocks/pull/52, which does exactly that. You can get it and some other changes on the latest version: https://pub.dev/packages/firebase_auth_mocks/changelog#083.
