### ISSUE TITLE
Bump Pubspec version

### ISSUE THREAD

**Issue by rayk** [atn832/firebase_auth_mocks#46]
HiGuy
0.8.1 is published to dart packages, but the pubspec in git is at 0.8.0. So the latest addition like ```userChanges``` are not being included.

Of course one can override their local pubspec to point to git and this works. Just a pain

**Comment by atn832** [comment]
What pubspec in git are you referring to? Dependencies should depend on your own project's pubspec.yaml, not the dependency's. So it should be unrelated to https://github.com/atn832/firebase_auth_mocks/blob/master/pubspec.yaml.

I just tried to add the dependency to firebase_auth_mock on a brand new project and it got the latest version:
```
% flutter pub add firebase_auth_mocks
Resolving dependencies...
  collection 1.15.0 (1.16.0 available)
+ equatable 2.0.3
  fake_async 1.2.0 (1.3.0 available)
+ firebase_auth 3.3.11
+ firebase_auth_mocks 0.8.3
+ firebase_auth_platform_interface 6.2.1
+ firebase_auth_web 3.3.9
+ firebase_core 1.13.1
+ firebase_core_platform_interface 4.2.5
+ firebase_core_web 1.6.1
  flutter_lints 1.0.4 (2.0.0 available)
+ flutter_web_plugins 0.0.0 from sdk flutter
+ http_parser 4.0.0
+ intl 0.17.0
+ js 0.6.4
  lints 1.0.1 (2.0.0 available)
  material_color_utilities 0.1.3 (0.1.4 available)
+ plugin_platform_interface 2.1.2
  source_span 1.8.1 (1.8.2 available)
  vector_math 2.1.1 (2.1.2 available)
Downloading firebase_auth_mocks 0.8.3...
Changed 13 dependencies!
```
