### ISSUE TITLE
Export MockUserCredential into firebase_auth_mocks.dart

### ISSUE THREAD

**Issue by mickaelalbertus** [atn832/firebase_auth_mocks#53]
Can we add the export MockUserCredential firebase_auth_mocks.dart in order to use MockUserCredential easily into our project?

**Comment by bibek-magar** [comment]
how r you using now?

**Comment by atn832** [comment]
You can create and pass a MockUser as shown in the readme (https://github.com/atn832/firebase_auth_mocks/blob/master/README.md). Do you have an example of how you'd want to use MockUserCredentials instead?

**Comment by atn832** [comment]
Feel free to open a new issue if you still have issues with the project.
