### ISSUE TITLE
Support for signInWithPopup

### ISSUE THREAD

**Issue by ga-bri-el** [atn832/firebase_auth_mocks#77]
Hey, I wanted to contribute with an implementation for `signInWithPopup`, however I came across the problem that `AuthProvider` is not exported. I wrote about this [here](https://github.com/firebase/flutterfire/discussions/9809).

Do you think there's a workaround to this? I'd be happy to contribute but other than having `AuthProvider` accessible, I don't know how :(

**Comment by atn832** [comment]
Thanks for taking a stab at it, @ga-bri-el!

If AuthProvider is listed in the automatically generated documentation (https://pub.dev/documentation/firebase_auth_platform_interface/latest/firebase_auth_platform_interface/AuthProvider-class.html), it means that it's exported.

I tried adding the `firebase_auth_platform_interface` dependency to firebase_auth_mocks and was able to import the dependency:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/3399854/198532333-3a1c028d-c390-4539-9541-dc245c1795fd.png">

You can probably close https://github.com/firebase/flutterfire/discussions/9809.

Let me know if you run into other issues.

**Comment by ga-bri-el** [comment]
Better late than never :-P
https://github.com/atn832/firebase_auth_mocks/pull/85

**Comment by atn832** [comment]
Thanks! In #85, you forgot to add the dependency `firebase_auth_platform_interface` to pubspec.yaml. So I did it in https://github.com/atn832/firebase_auth_mocks/commit/4fb29234cbfe77102f6d1757e9485e3f560955ce.

**Comment by atn832** [comment]
Just published your PR to version 0.9.3. https://pub.dev/packages/firebase_auth_mocks/changelog#093.

**Comment by ga-bri-el** [comment]
@atn832 oops, sorry about that!

Thanks a lot
