### ISSUE TITLE
The getter 'user' was called on null.

### ISSUE THREAD

**Issue by brmel** [atn832/firebase_auth_mocks#8]
Hi, 
I am having a problem testing signInWithEmailAndPassword(), the AuthResult I get after running the test is null, I tried to run the exact example you gave but still getting the same error: 

    test('with email and password', () async {
      final auth = MockFirebaseAuth();
      final result = await auth.signInWithEmailAndPassword(
          email: 'some email', password: 'some password');
      final user = await result.user;
      expect(user.uid, isNotEmpty);
      expect(user.displayName, isNotEmpty);
    });

the error I get is : 
NoSuchMethodError: The getter 'user' was called on null.
Receiver: null
Tried calling: user

the result object is null and I really do not know why. I do not know if you faced this issu before, but I appreciate your help. 
Thank you

**Comment by atn832** [comment]
Did you update your yaml file to use the latest version of the library? See https://pub.dev/packages/firebase_auth_mocks#-installing-tab-.

**Comment by brmel** [comment]
it worked all fine after the update, thank you !
