### ISSUE TITLE
Request: add _maybeThrowException() to reload method

### ISSUE THREAD

**Issue by bianca8** [atn832/firebase_auth_mocks#93]
Hi there!
It is impossibile to throw an exception with reload method,
I read your code, in MockUser and in method reload() is missing _maybeThrowException(), for this reason it is impossible to test exception in reload method.

**Comment by atn832** [comment]
Thanks for reporting the issue. It's now fixed in the latest version. https://pub.dev/packages/firebase_auth_mocks/changelog#0110
